### ISSUE TITLE
provide "strict" validation mode

### ISSUE THREAD

**Issue by pbcornell** [amazon-ion/ion-schema-kotlin#57]
While open content is generally great for distributed systems development, there are times when it is helpful for validation to fail on open content (to catch spelling errors, for example).  Consider adding a "strict" validation mode to support this use case.

**Comment by popematt** [comment]
Related to https://github.com/amazon-ion/ion-schema-kotlin/issues/179

This issue is no longer relevant for Ion Schema 2.0 because ISL 2.0 does not allow any arbitrary open content.
